### PR TITLE
Sample GLTF loader

### PR DESCRIPTION
**Pull request by bernardkwok**
**GLTF geometry only loader**
 
 - Used cgltf for loading
 - Does not support creating transform instances of geometry as this is not supported in the viewer
 - Does not handle materials or texture dependencies
 - Modified the viewer to handle multiple meshes.
 
 Example use boombox shader from Ed but using original GLTF model vs obj version.
 Note that the gltf branch and the boombox branches have been merged into this branch.
 
image

Multiple mesh example (no gltf shader for this as yet)
image

### CODE REVIEW

**Comment by emackey** [comment]
This is great, I'm able to compile & run this, and several sample models load right in.

Would it be possible to automatically construct a MaterialX document similar to `gltf_pbr_boombox.mtlx` based on the glTF material definition read by cgltf?  It would need to construct a `<tiledimage ...>` for each texture found, and a `<gltf_pbr ...>` with the glTF texture & factor wireup.

**Comment by bernardkwok** [comment]
Hi @emackey 
Yes. This is possible. I think it might be best to write a separate utility which can do this conversion process which can be called either standalone or part of an import process. Guess this would be "undistilling" and the counterpart would be the "distilling" process which is TBD.

I would need some guidance to know how to parse extensions properly. The generation of a MTLX graph would then be very straight forward.

The other avenue to be looked at is if we add an extension for a direct MTLX payload (presumably in JSON format) what would this look like. @ashwinbhat is looking around in this area.

**Comment by emackey** [comment]
Hi @bernardkwok, I see https://github.com/materialx/MaterialX/pull/841 also got closed.  Is there a plan to bring this into the main repo?

**Comment by kwokcb** [comment]
Hi @emackey, I would like to move this into the main repo but put up the PR prematurely by accident. 
I'd like to raise this with Jonathan Stone offline to see how to proceed. I've created a new branch to bring this up to speed with the current MaterialX repo for now.

**Comment by kwokcb** [comment]
This is now a formal PR against ASWF main: https://github.com/materialx/MaterialX/pull/846.

**Pull request closed without merging**
